### ISSUE TITLE
apply all spartanization tips

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team1#48] opened 2018-11-07 17:35 UTC
![image](https://user-images.githubusercontent.com/12775400/48151716-ac7dd900-e2ca-11e8-8f7b-315c18f0cd26.png)

**Comment by yossigil** [comment] 2018-11-07 18:22
Best to get a screen dump of each user's screen to make sure it is ok.

**Comment by Matanpugach** [comment] 2018-11-07 18:53
@ShaiZeevi @YarinSh @yoavz1997 @ShaiZeevi @ofiralexi @saifun @Itamaror I think we should all install the spartinizer plugin. @YarinSh , how did you install the spartanizer plugin?

**Comment by YarinSh** [comment] 2018-11-07 20:13
@yossigil Some of the tips are to re-write azzert.assertTrue for example, to a simple assert which contradicts #43 - as we should use the azzert. For example:
![image](https://user-images.githubusercontent.com/32907017/48158121-4d27c500-e2da-11e8-8224-ab489d471bdf.png)
How should I handle these tips?

**Comment by ShaiZeevi** [comment] 2018-11-08 11:35
Duplicate of #37

**Closed by ShaiZeevi** 2018-11-08 11:35 UTC
Labels: spartanizer plugin
